language: python
sudo: false
matrix:
  include:
  - python: '3.8'
  - python: '3.9'
  - python: '3.10-dev'
  - python: 'nightly'
  - python: 'pypy3'
  allow_failures:
  - python: 'nightly'
before_install:
- python -m pip install --upgrade pip
- pip install "poetry<1.2"
install:
- poetry install
script:
- poetry run pytest
after_success:
- codecov
